const fs = require('fs');
const path = require('path');

function parseGcodeMetadata(filePath) {
  try {
    const stats = fs.statSync(filePath);
    const fd = fs.openSync(filePath, 'r');
    
    // Read first 16KB and last 128KB (metadata often at the end in PrusaSlicer/Bambu)
    const START_SIZE = 16384;
    const END_SIZE = 131072;
    
    const startBuffer = Buffer.alloc(Math.min(START_SIZE, stats.size));
    fs.readSync(fd, startBuffer, 0, startBuffer.length, 0);
    
    const endBuffer = Buffer.alloc(Math.min(END_SIZE, stats.size));
    fs.readSync(fd, endBuffer, 0, endBuffer.length, Math.max(0, stats.size - END_SIZE));
    fs.closeSync(fd);

    const content = startBuffer.toString() + "\n---END---\n" + endBuffer.toString();
    const metadata = {};

    const patterns = {
      layerHeight: [
        /;\s*layer_height\s*=\s*([\d.]+)/i, 
        /;\s*Layer height:\s*([\d.]+)/i, 
        /;\s*SETTING_3.*layer_height\\n([\d.]+)/,
        /G1.*Z([\d.]+).*Layer height/i,
        /;\s*HEIGHT:([\d.]+)/i
      ],
      infill: [
        /;\s*sparse_infill_density\s*=\s*([\d.]+)%/i,
        /;\s*infill_percentage\s*=\s*([\d.]+)/i, 
        /;\s*Infill density:\s*([\d.]+)/i, 
        /;\s*SETTING_3.*infill_sparse_density\\n([\d.]+)/,
        /;\s*fill_density\s*=\s*([\d.]+)/i
      ],
      printTime: [
        /;\s*estimated printing time \(normal mode\)\s*=\s*([^\n\r]+)/i,
        /;\s*estimated_print_time\s*=\s*([^\n\r]+)/i, 
        /;\s*TIME:(\d+)/i, 
        /;\s*print_time\s*:\s*(\d+)/i,
        /;\s*total_time\s*:\s*([^\n\r]+)/i,
        /;\s*estimated_time\s*:\s*([^\n\r]+)/i
      ],
      filamentUsed: [
        /;\s*filament used \[m\]\s*=\s*([\d.]+)/i,
        /;\s*Filament used:\s*([\d.]+m)/i,
        /;\s*filament_used\s*=\s*([\d.]+)/i, 
        /;\s*filament used \[mm\]\s*=\s*([\d.]+)/i
      ],
      slicer: [
        /;\s*generated by ([\w\s.]+)/i, 
        /;\s*Slicer: ([\w\s.]+)/i, 
        /;\s*Slicer\s*:\s*([\w\s.]+)/i,
        /;\s*Klipper info: ([\w\s.]+)/i
      ],
      filamentType: [
        /;\s*filament_type\s*=\s*([^\r\n]+)/i,
        /;\s*material_type\s*=\s*([^\r\n]+)/i
      ],
      printerModel: [
        /;\s*printer_model\s*=\s*([^\n\r]+)/i,
        /;\s*machine_type\s*=\s*([^\n\r]+)/i
      ],
      weight: [
        /;\s*total filament used \[g\]\s*=\s*([\d.]+)/i,
        /;\s*filament_weight\s*=\s*([\d.]+)/i,
        /;\s*filament used \[g\]\s*=\s*([\d.]+)/i
      ],
      supports: [
        /;\s*support_material\s*=\s*([01])/i
      ],
      tempNozzle: [
        /;\s*nozzle_temperature\s*=\s*([^\r\n]+)/i,
        /;\s*first_layer_temperature\s*=\s*([^\r\n]+)/i,
        /;\s*temperature\s*=\s*([^\r\n]+)/i,
        /M104\s+S([1-9]\d{2,})/i
      ],
      tempBed: [
        /;\s*hot_plate_temp\s*=\s*([^\r\n]+)/i,
        /;\s*textured_plate_temp\s*=\s*([^\r\n]+)/i,
        /;\s*bed_temperature\s*=\s*([^\r\n]+)/i,
        /;\s*first_layer_bed_temperature\s*=\s*([^\r\n]+)/i,
        /M140\s+S([3-9]\d+)/i
      ]
    };

    const getDominantValue = (str) => {
      if (!str) return null;
      // Handle both semicolon and comma separators
      const parts = str.split(/[;,]/).map(p => p.trim()).filter(p => p);
      if (parts.length <= 1) return str;
      
      const counts = {};
      parts.forEach(p => counts[p] = (counts[p] || 0) + 1);
      return Object.entries(counts).sort((a,b) => b[1] - a[1])[0][0];
    };

    for (const [key, regexes] of Object.entries(patterns)) {
      for (const regex of regexes) {
        const match = content.match(regex);
        if (match) {
          let val = match[1].trim();
          
          // Use dominant value for almost everything that can be multi-value
          if (['filamentType', 'tempNozzle', 'tempBed', 'layerHeight', 'infill'].includes(key)) {
            val = getDominantValue(val);
          }
          
          metadata[key] = val;
          break;
        }
      }
    }

    console.log(`Parsed G-code metadata for ${path.basename(filePath)}:`, metadata);

    // Format print time if it's in seconds (Cura)
    if (metadata.printTime && /^\d+$/.test(metadata.printTime)) {
      const totalSecs = parseInt(metadata.printTime);
      const h = Math.floor(totalSecs / 3600);
      const m = Math.floor((totalSecs % 3600) / 60);
      metadata.printTime = h > 0 ? `${h}h ${m}m` : `${m}m`;
    }

    return Object.keys(metadata).length ? metadata : null;
  } catch (e) {
    console.error('Error parsing G-code:', e);
    return null;
  }
}

function extractGcodeThumbnail(filePath, outputDir) {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    const thumbRegex = /;\s*thumbnail\s+begin\s+(\d+)x(\d+)\s+(\d+)\s*([\s\S]+?);\s*thumbnail\s+end/i;
    const match = content.match(thumbRegex);
    if (!match) return null;

    const base64Data = match[4].replace(/;\s*/g, '').trim();
    const filename = `thumb_${Date.now()}.png`;
    const outputPath = path.join(outputDir, filename);
    fs.writeFileSync(outputPath, Buffer.from(base64Data, 'base64'));
    return filename;
  } catch (e) {
    console.error('Failed to extract G-code thumbnail:', e);
    return null;
  }
}

module.exports = { parseGcodeMetadata, extractGcodeThumbnail };
