const fs = require('fs');
const path = require('path');

function parseGcodeMetadata(filePath) {
  try {
    const stats = fs.statSync(filePath);
    const fd = fs.openSync(filePath, 'r');
    
    // Read first 16KB and last 128KB (metadata often at the end in PrusaSlicer/Bambu)
    const START_SIZE = 16384;
    const END_SIZE = 131072;
    
    const startBuffer = Buffer.alloc(Math.min(START_SIZE, stats.size));
    fs.readSync(fd, startBuffer, 0, startBuffer.length, 0);
    
    const endBuffer = Buffer.alloc(Math.min(END_SIZE, stats.size));
    fs.readSync(fd, endBuffer, 0, endBuffer.length, Math.max(0, stats.size - END_SIZE));
    fs.closeSync(fd);

    const content = startBuffer.toString() + "\n---END---\n" + endBuffer.toString();
    const metadata = {};

    const patterns = {
      layerHeight: [
        /;\s*layer_height\s*=\s*([\d.]+)/i, 
        /;\s*Layer height:\s*([\d.]+)/i, 
        /;\s*SETTING_3.*layer_height\\n([\d.]+)/,
        /G1.*Z([\d.]+).*Layer height/i,
        /;\s*HEIGHT:([\d.]+)/i
      ],
      infill: [
        /;\s*sparse_infill_density\s*=\s*([\d.]+)%/i,
        /;\s*infill_percentage\s*=\s*([\d.]+)/i, 
        /;\s*Infill density:\s*([\d.]+)/i, 
        /;\s*SETTING_3.*infill_sparse_density\\n([\d.]+)/,
        /;\s*fill_density\s*=\s*([\d.]+)/i
      ],
      printTime: [
        /;\s*estimated printing time \(normal mode\)\s*=\s*([^\n\r]+)/i,
        /;\s*estimated_print_time\s*=\s*([^\n\r]+)/i, 
        /;\s*TIME:(\d+)/i, 
        /;\s*print_time\s*:\s*(\d+)/i,
        /;\s*total_time\s*:\s*([^\n\r]+)/i,
        /;\s*estimated_time\s*:\s*([^\n\r]+)/i
      ],
      filamentUsed: [
        /;\s*filament_used\s*=\s*([\d.]+)/i, 
        /;\s*Filament used:\s*([\d.]+m)/i,
        /;\s*filament used \[mm\]\s*=\s*([\d.]+)/i
      ],
      slicer: [
        /;\s*generated by ([\w\s.]+)/i, 
        /;\s*Slicer: ([\w\s.]+)/i, 
        /;\s*Slicer\s*:\s*([\w\s.]+)/i,
        /;\s*Klipper info: ([\w\s.]+)/i
      ]
    };

    for (const [key, regexes] of Object.entries(patterns)) {
      for (const regex of regexes) {
        const match = content.match(regex);
        if (match) {
          metadata[key] = match[1].trim();
          break;
        }
      }
    }

    console.log(`Parsed G-code metadata for ${path.basename(filePath)}:`, metadata);

    // Format print time if it's in seconds (Cura)
    if (metadata.printTime && /^\d+$/.test(metadata.printTime)) {
      const totalSecs = parseInt(metadata.printTime);
      const h = Math.floor(totalSecs / 3600);
      const m = Math.floor((totalSecs % 3600) / 60);
      metadata.printTime = h > 0 ? `${h}h ${m}m` : `${m}m`;
    }

    return Object.keys(metadata).length ? metadata : null;
  } catch (e) {
    console.error('Error parsing G-code:', e);
    return null;
  }
}

function extractGcodeThumbnail(filePath, outputDir) {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    const thumbRegex = /;\s*thumbnail\s+begin\s+(\d+)x(\d+)\s+(\d+)\s*([\s\S]+?);\s*thumbnail\s+end/i;
    const match = content.match(thumbRegex);
    if (!match) return null;

    const base64Data = match[4].replace(/;\s*/g, '').trim();
    const filename = `thumb_${Date.now()}.png`;
    const outputPath = path.join(outputDir, filename);
    fs.writeFileSync(outputPath, Buffer.from(base64Data, 'base64'));
    return filename;
  } catch (e) {
    console.error('Failed to extract G-code thumbnail:', e);
    return null;
  }
}

module.exports = { parseGcodeMetadata, extractGcodeThumbnail };
